services:
  vault:
    image: andyb/vault-benchmark-vault:${GIT_REV}
    container_name: vault
    depends_on:
      - statsd
    build:
      context: ..
      dockerfile_inline: |
        # syntax=docker/dockerfile:1
        FROM golang:bookworm AS build
        # Switch from sh -> bash
        SHELL ["/bin/bash", "-c"]
        
        # Install Volta to install npm to install yarn
        RUN <<EOF
          echo "Downloading and executing Volta installation script"
          # Compress the script a bit to dump it for record-keeping
          curl -s 'https://get.volta.sh' | tee /tmp/install-volta.sh | tr -d '\n'
          bash /tmp/install-volta.sh; rm /tmp/install-volta.sh
          echo
          source ~/.bashrc
        EOF
        # Save Volta env vars
        ENV VOLTA_HOME="/root/.volta"
        ENV PATH="$$VOLTA_HOME/bin:$$PATH"
        
        # Compile Vault
        ADD . /build/
        WORKDIR /build
        # Install tooling in package dir to use pinned versions
        RUN cd ./ui/; volta install node yarn
        RUN make bootstrap
        RUN make ci-build-ui
        RUN make ci-build
        
        # Prepare runtime image
        FROM golang:1.23.3-bookworm
        # Install tools
        RUN <<EOF
          apt-get update && apt-get install -y curl wget inotify-tools procps
        EOF
        # Add vault-benchmark
        #RUN go install github.com/hashicorp/vault-benchmark@2e01cb8f5cc4f02967fa2d187868126f4eb851ac
        RUN <<EOF
          git clone https://github.com/andybao-dd/vault-benchmark.git /vault-benchmark-andyb
          cd /vault-benchmark-andyb
          git checkout 2e01cb8f5cc4f02967fa2d187868126f4eb851ac
          go install
        EOF
        # Add Vault
        COPY --from=build --link /build/dist/vault /usr/bin/vault
    ports:
      - "127.0.0.1:8200:8200"
    volumes:
      # In-memory filesystem for testing
      - type: tmpfs
        target: /scratch
        tmpfs:
          size: 3000000000 # 3 GB
      - ./vault-config.hcl:/config.hcl:ro
      - ./bench.hcl:/bench.hcl:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
      - ./out:/out:rw
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_DEV_LISTEN_ADDRESS : "127.0.0.1:8200"
    command: ["bash", "/entrypoint.sh"]
    privileged: true

  statsd:
    image: atlassianlabs/gostatsd:40.0.0
    container_name: vault-benchy-statsd
    hostname: vault-benchy-statsd
    volumes:
      - ./statsd.toml:/statsd.toml:ro
      - ./out:/out:rw
    entrypoint: ["/bin/sh", "-c", "gostatsd --json --config-path ./statsd.toml 2>/out/statsd-stderr.log 1>/out/statsd-stdout.log"]